#
# Copyright OpenSearch Contributors
# SPDX-License-Identifier: Apache-2.0
#
# The OpenSearch Contributors require contributions made to
# this file be licensed under the Apache-2.0 license or a
# compatible open source license.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: data-prepper-config
  namespace: opensearch
data:
  pipelines.yaml: |
    simple-pipeline:
      source:
        http:
          port: 2021
      sink:
        - stdout: